Fix: linting error/missing starting space in comment
These look like spaces but aren't and fail linting checks with:

  Error: 70:6 [comments] missing starting space in comment
  Error: 106:6 [comments] missing starting space in comment

Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>